-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 19:12:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RWA2022dkajzogaj20
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RWA2022dkajzogaj20
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RWA2022dkajzogaj20` DEFAULT CHARACTER SET utf8 ;
USE `RWA2022dkajzogaj20` ;

-- -----------------------------------------------------
-- Table `RWA2022dkajzogaj20`.`Uloge_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RWA2022dkajzogaj20`.`Uloge_korisnika` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `opis` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RWA2022dkajzogaj20`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RWA2022dkajzogaj20`.`Korisnik` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `korime` VARCHAR(45) NOT NULL,
  `lozinka` TEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `aktivacijski_kod` INT NULL,
  `totp_kljuc` VARCHAR(200) NULL,
  `Uloge_korisnika_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Korisnik_Uloge_korisnika_idx` (`Uloge_korisnika_id` ASC) VISIBLE,
  CONSTRAINT `fk_Korisnik_Uloge_korisnika`
    FOREIGN KEY (`Uloge_korisnika_id`)
    REFERENCES `RWA2022dkajzogaj20`.`Uloge_korisnika` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RWA2022dkajzogaj20`.`Filmovi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RWA2022dkajzogaj20`.`Filmovi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `odrasli` TINYINT NOT NULL,
  `pozadina_url` VARCHAR(100) NULL,
  `budzet` INT NOT NULL,
  `tmdb_url` VARCHAR(100) NOT NULL,
  `id_tmdb` INT NOT NULL,
  `id_imdb` INT NULL,
  `jezik` VARCHAR(45) NOT NULL,
  `izvorni_naslov` VARCHAR(100) NOT NULL,
  `opis` TEXT NULL,
  `popularnost` INT NOT NULL,
  `poster_url` VARCHAR(100) NULL,
  `datum_objave` DATE NOT NULL,
  `prihod` INT NOT NULL,
  `vrijeme_trajanja` INT NULL,
  `status` VARCHAR(45) NOT NULL,
  `tagline` VARCHAR(70) NULL,
  `naslov` VARCHAR(70) NOT NULL,
  `video` TINYINT NOT NULL,
  `prosjek_glasanja` DECIMAL(3) NOT NULL,
  `brojevi_glasova` INT NOT NULL,
  `datum_unosa` DATE NULL,
  `total_results` INT NOT NULL,
  `total_pages` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RWA2022dkajzogaj20`.`Zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RWA2022dkajzogaj20`.`Zanr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `opis` TEXT NULL,
  `id_tmdb` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RWA2022dkajzogaj20`.`Filmovi_Zanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RWA2022dkajzogaj20`.`Filmovi_Zanr` (
  `Filmovi_id` INT NOT NULL,
  `Zanr_id` INT NOT NULL,
  PRIMARY KEY (`Filmovi_id`, `Zanr_id`),
  INDEX `fk_Filmovi_has_Zanr_Zanr1_idx` (`Zanr_id` ASC) VISIBLE,
  INDEX `fk_Filmovi_has_Zanr_Filmovi1_idx` (`Filmovi_id` ASC) VISIBLE,
  CONSTRAINT `fk_Filmovi_has_Zanr_Filmovi1`
    FOREIGN KEY (`Filmovi_id`)
    REFERENCES `RWA2022dkajzogaj20`.`Filmovi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Filmovi_has_Zanr_Zanr1`
    FOREIGN KEY (`Zanr_id`)
    REFERENCES `RWA2022dkajzogaj20`.`Zanr` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
